title: COMP5202
author: Jeffrey Kranenburg

email: jk11@g.toiohomai.ac.nz
description: > 
  This course covers an introduction to programming using C#, Javascript and later on Swift. The focus is not the languages, but rather the concepts and being able to transfer between different languages.
baseurl: "/"
url: "/" 
twitter_username: jwknz
github_username:  bcsjk11
slackclass: comp5202-17b
slacktutor: jeff

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed